### PR TITLE
Build in a machanism to stay below the 120/min threshold

### PR DESCRIPTION
**Pull request by Aspire1Inspire2**
Here is what I did:
Define a num_queries inside of the client class. Count the number of queries per given 'Date'. If the number of queries reached 120 and the user is still trying to query, the code will sleep into the next minute 'on the server'.

To ensure we slept into the next minute 'on the server', 5 extra seconds of sleep time is used. A network delay time is calculated based on the difference between the query time and the returned time flag. Also, this network delay is used in refreshing access token. 

One exception is that the queries to the accounts and the order endpoints are not counted towards the query threshold limit. This is following what the offcial documentation said.

Also removed an extra slash '/' used in one of the accounts endpoint.

Theoretically, after this pull request, the `ExdLmtError` and status_code=429 should not happen any more. The code will be more robust and will avoid dev account penalty for excceeding limit too many times a day.

This pull requst resolves issue #66

### CODE REVIEW

**Comment by Aspire1Inspire2** [comment]
Hi, is there anything that you don't like about this PR that I can help with?

Thanks.

**Comment by Aspire1Inspire2** [comment]
There are several things that probably can be removed or improved if you don't like them:
1. network_delay is probably not necessary for most users since we have a 5 seconds protection.
2. The 5 seconds protection can probably be smaller.

Other than these, I think this PR is a fair improvement to the current library's stability.

**Comment by Aspire1Inspire2** [comment]
I removed the network delay time as it can be compensated by the user by customizing the qry_lmt_prtc_delay in the __init__ call.
Also Default the protection margin to 1 second to allow better performance.
Please read the comments in the source code. I've elaborated the change.
The logic is now much simpler.

**Comment by Aspire1Inspire2** [comment]
As the master branch has been updated. I also sync up the latest git repo with this pull request.
I would really appreciate if you could spend some time reading and test the pull request. I think this is a very important feature that is missing in the current implementation.

**Comment by areed1192** [comment]
So I looked over the code and I'm trying to understand the 4-second delay that you specify when you initialize the client. Can you elaborate on what that is intended to do?

**Comment by Aspire1Inspire2** [comment]
Hi, sorry for the late reply. I just noticed the comment.
The 4 seconds default was experienced from trial and error. 
I still occasionally get 429 error indicating that I exceed 120 limitation when using 3 seconds setup.

If you do not like the default, you can default it to 0 seconds. Then let the user determine how much they want to delay by themselves.

To explain why we need a delay:
Sometimes the local time and server time is not in sync. The moment you thought you are safe because you are querying in the "next following minute" can still give you error 429 of over querying.

Could you let me know if you further explanation on the implementation?
If you determined that this feature is not needed in the library, could you also let me know?

**Comment by Aspire1Inspire2** [comment]
```
       qry_lmt_prtc_delay {float} -- Query limit protection delay, in seconds. A dis-sync of client time 
            and Server time can cause the first query in the subsequent minute incorrectly counted towards 
            the previous minute on the Server, thus throwing 429 ExdLmtError. Delay the first query at each
            client minute by this amount to protect against the mentioned situation. Default to 4s.
```

**Comment by Aspire1Inspire2** [comment]
One additional comment:
The `qry_lmt_prtc_delay {float} -- Query limit protection delay` will be triggered ***when and only when*** user exceed 120/min threshold at current server minute. It will never sleep if user does not exceed 120/min threshold. 

1. Assume one user never exceed the threshold, the user will never experience performance impact due to the sleep time setup.
2. Assume one user exceed the threshold, the user will never experience performance impact if the sleep time is set to 0s.
3. Assume one user exceed the threshold, the user will experience performance impact for configured sleep time. However, this is to protect the user from being thrown 429 error and execution terminated. This sleep time can be configured by the user using the class initiator.

I want to emphasize one more time: if you do not agree on the default time of 4s, you can default it to 0. It will not affect in any way how the code is running right now.

Please let me know if you have any concern. Thank you.

**Pull request closed without merging**
